### ISSUE TITLE
Execution time is computed as an integer, should be as a double

### ISSUE THREAD

**Issue by computations** [prabhavk/mst-backbone-repo#2]
An example is 

```
CPU time used for computing subtree with 16 leaves is 0 seconds
```

which is less accurate than what could be printed. The code to compute a message like this is

```
timeTakenToComputeSubtree = chrono::duration_cast<chrono::seconds>(t_end_time - t_start_time);			
cout << "CPU time used for computing subtree with " << this->t->numberOfObservedVertices << " leaves is " << timeTakenToComputeSubtree.count() << " seconds\n";
this->mstBackboneLogFile << "CPU time used for computing subtree with " << this->t->numberOfObservedVertices << " leaves is " << timeTakenToComputeSubtree.count() << " seconds\n";
```
In this case, the solution is to declare `timeTakenToComputeSubtree`  as a `std::chrono::duration<double>`. This produces a duration, with a default ratio of seconds (i.e. the result from `.count()` will be in seconds).

**Comment by prabhavk** [comment]
Thanks for pointing this out. 

I see the following being printed after incorporating your suggestion. 

CPU time used for computing subtree with 16 leaves is 0.0655484 seconds.
